[package]
name = "global_env"
version = "0.1.0"
edition = "2024"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
windows = { version = "0.62.0", features = ["Win32", "Win32_UI_WindowsAndMessaging"] }

[lib]
name = "global_env"
version = "0.1.0"
edition = "2024"